package com.icure.cardinal.bridge.bench.support

import com.icure.cardinal.sdk.CardinalSdk
import com.icure.cardinal.sdk.api.raw.RawApiConfig
import com.icure.cardinal.sdk.api.raw.RawMessageGatewayApi
import com.icure.cardinal.sdk.api.raw.impl.RawAnonymousAuthApiImpl
import com.icure.cardinal.sdk.api.raw.impl.RawGroupApiImpl
import com.icure.cardinal.sdk.api.raw.impl.RawHealthcarePartyApiImpl
import com.icure.cardinal.sdk.api.raw.impl.RawUserApiImpl
import com.icure.cardinal.sdk.auth.UsernamePassword
import com.icure.cardinal.sdk.auth.services.AuthProvider
import com.icure.cardinal.sdk.crypto.CryptoStrategies
import com.icure.cardinal.sdk.model.DataOwnerWithType
import com.icure.cardinal.sdk.model.DatabaseInitialisation
import com.icure.cardinal.sdk.model.HealthcareParty
import com.icure.cardinal.sdk.model.User
import com.icure.cardinal.sdk.model.specializations.Base64String
import com.icure.cardinal.sdk.options.AuthenticationMethod
import com.icure.cardinal.sdk.options.BasicSdkOptions
import com.icure.cardinal.sdk.options.RequestRetryConfiguration
import com.icure.cardinal.sdk.options.SdkOptions
import com.icure.cardinal.sdk.options.getAuthProvider
import com.icure.cardinal.sdk.storage.impl.VolatileStorageFacade
import com.icure.cardinal.sdk.utils.Serialization
import com.icure.cardinal.sdk.utils.base64Encode
import com.icure.kryptom.crypto.CryptoService
import com.icure.kryptom.crypto.RsaAlgorithm
import com.icure.kryptom.crypto.defaultCryptoService
import com.icure.utils.InternalIcureApi
import io.ktor.client.HttpClient
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.serialization.kotlinx.json.json
import kotlinx.coroutines.delay
import kotlin.time.Duration.Companion.seconds
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/**
 * A healthcare party with a key generated by the test, and a Cardinal SDK logged in as its user.
 *
 * [pkcs8] is the private key of the healthcare party, as the bridge expects it when creating a session.
 */
class BenchHcp(
	val login: String,
	val password: String,
	val hcpId: String,
	val pkcs8: Base64String,
	val sdk: CardinalSdk,
)

/**
 * A test group of the Kraken started by [Containers], in which healthcare parties can be created with [createHcp].
 */
@OptIn(InternalIcureApi::class, ExperimentalUuidApi::class)
class BenchGroup internal constructor(
	private val krakenUrl: String,
	private val groupId: String,
	private val superAdminAuth: AuthProvider,
	private val rawApiConfig: RawApiConfig,
) {
	/**
	 * Creates a healthcare party with an admin user in the group, and initialises a Cardinal SDK as that user, which
	 * creates the key of the healthcare party.
	 */
	suspend fun createHcp(lastName: String): BenchHcp {
		val hcp = RawHealthcarePartyApiImpl(krakenUrl, superAdminAuth, rawApiConfig).createHealthcarePartyInGroup(
			groupId,
			HealthcareParty(id = Uuid.random().toString(), firstName = "Bench", lastName = lastName),
		).successBody()

		val login = "bench-${Uuid.random()}@icure.com"
		val password = "bench-${Uuid.random()}"
		RawUserApiImpl(krakenUrl, superAdminAuth, rawApiConfig).createAdminUserInGroup(
			groupId,
			User(id = Uuid.random().toString(), login = login, email = login, passwordHash = password, healthcarePartyId = hcp.id),
		).successBody()

		val keyPair = defaultCryptoService.rsa.generateKeyPair(RsaAlgorithm.RsaEncryptionAlgorithm.OaepWithSha256)
		val sdk = CardinalSdk.initialize(
			projectId = null,
			baseUrl = krakenUrl,
			authenticationMethod = AuthenticationMethod.UsingCredentials(UsernamePassword(login, password)),
			baseStorage = VolatileStorageFacade(),
			options = SdkOptions(
				cryptoStrategies = object : CryptoStrategies {
					override suspend fun generateNewKeyForDataOwner(
						self: DataOwnerWithType,
						cryptoPrimitives: CryptoService
					): CryptoStrategies.KeyGenerationRequestResult =
						CryptoStrategies.KeyGenerationRequestResult.Use(keyPair)
				}
			)
		)
		return BenchHcp(
			login = login,
			password = password,
			hcpId = hcp.id,
			pkcs8 = defaultCryptoService.rsa.exportPrivateKeyPkcs8(keyPair.private).base64Encode(),
			sdk = sdk,
		)
	}
}

/**
 * Bootstraps the Kraken started by [Containers] with a superadmin and a test group.
 */
@OptIn(InternalIcureApi::class, ExperimentalUuidApi::class)
object ICureBootstrap {
	private const val SUPER_ADMIN = "john"
	private const val SUPER_ADMIN_PASSWORD = "LetMeIn"

	/** SHA-256 of [SUPER_ADMIN_PASSWORD]. */
	private const val SUPER_ADMIN_PASSWORD_SHA256 = "1796980233375ccd113c972d946b2c4a7892e4f69c60684cfa730150047f9c0b"

	private val defaultRoles = mapOf(
		"PATIENT" to listOf("BASIC_USER", "BASIC_DATA_OWNER"),
		"HCP" to listOf("BASIC_USER", "BASIC_DATA_OWNER", "PATIENT_USER_MANAGER", "LEGACY_MESSAGE_MANAGER", "HIERARCHICAL_DATA_OWNER"),
		"DEVICE" to listOf("BASIC_USER", "BASIC_DATA_OWNER"),
		"USER" to listOf("BASIC_USER"),
	)

	private val httpClient = HttpClient {
		install(ContentNegotiation) {
			json(json = Serialization.json)
		}
	}

	private val rawApiConfig = RawApiConfig(
		httpClient = httpClient,
		additionalHeaders = emptyMap(),
		requestTimeout = null,
		json = Serialization.json,
		retryConfiguration = RequestRetryConfiguration(),
	)

	suspend fun createGroup(krakenUrl: String, couchDbUrl: String): BenchGroup {
		bootstrapCloud(
			httpClient = httpClient,
			groupId = "xx",
			groupPassword = "xx",
			groupUserId = Uuid.random().toString(),
			groupUserLogin = SUPER_ADMIN,
			groupUserPasswordHash = SUPER_ADMIN_PASSWORD_SHA256,
			couchDbUrl = couchDbUrl,
			couchDbUser = Containers.COUCHDB_USERNAME,
			couchDbPassword = Containers.COUCHDB_PASSWORD,
			rootUserRoles = defaultRoles,
			defaultQuotas = listOf(1000, 10, 5),
		)
		delay(1.seconds)

		val superAdminAuth = AuthenticationMethod.UsingCredentials(UsernamePassword(SUPER_ADMIN, SUPER_ADMIN_PASSWORD))
			.getAuthProvider(
				authApi = RawAnonymousAuthApiImpl(apiUrl = krakenUrl, rawApiConfig = rawApiConfig),
				cryptoService = defaultCryptoService,
				projectId = null,
				options = BasicSdkOptions(),
				messageGatewayApi = RawMessageGatewayApi(httpClient, defaultCryptoService),
				krakenUrl = krakenUrl,
			)

		val groupId = "bench-${Uuid.random()}"
		RawGroupApiImpl(krakenUrl, superAdminAuth, rawApiConfig).createGroup(
			id = groupId,
			name = groupId,
			password = defaultCryptoService.strongRandom.randomUUID(),
			superGroup = "xx",
			initialisationData = DatabaseInitialisation(users = emptyList(), healthcareParties = emptyList()),
		).successBody()

		return BenchGroup(krakenUrl, groupId, superAdminAuth, rawApiConfig)
	}
}
